# clearml.conf
[api]
web_server = http://localhost:8080
api_server = http://localhost:8008
files_server = http://localhost:8081

[sdk.aws.s3]
region = ""

[sdk.google.storage]

[sdk.development]
default_output_uri = ""